'use strict';

var amediaDomains = [
  'www.aasavis.no',
  'www.amta.no',
  'www.an.no',
  'www.auraavis.no',
  'www.austagderblad.no',
  'www.avisa-valdres.no',
  'www.avisnavn.no',
  'www.ba.no',
  'www.blv.no',
  'www.budstikka.no',
  'www.bygdeposten.no',
  'www.dt.no',
  'www.eikerbladet.no',
  'www.enebakkavis.no',
  'www.f-b.no',
  'www.firda.no',
  'www.firdaposten.no',
  'www.fremover.no',
  'www.gd.no',
  'www.gjengangeren.no',
  'www.glomdalen.no',
  'www.h-avis.no',
  'www.ha-halden.no',
  'www.hadeland.no',
  'www.hamar-dagblad.no',
  'www.hardanger-folkeblad.no',
  'www.hblad.no',
  'www.helg.no',
  'www.ialta.no',
  'www.ifinnmark.no',
  'www.indre.no',
  'www.jarlsbergavis.no',
  'www.kv.no',
  'www.kvinnheringen.no',
  'www.laagendalsposten.no',
  'www.lierposten.no',
  'www.lofot-tidende.no',
  'www.lofotposten.no',
  'www.moss-avis.no',
  'www.noblad.no',
  'www.nord24.no',
  'www.norddalen.no',
  'www.nordhordland.no',
  'www.nordlys.no',
  'www.oa.no',
  'www.oblad.no',
  'www.op.no',
  'www.ostlendingen.no',
  'www.oyene.no',
  'www.pd.no',
  'www.polkaposten.no',
  'www.r-a.no',
  'www.rablad.no',
  'www.ranablad.no',
  'www.rb.no',
  'www.retten.no',
  'www.rha.no',
  'www.ringblad.no',
  'www.ringsaker-blad.no',
  'www.sa.no',
  'www.salsaposten.no',
  'www.sandeavis.no',
  'www.sb.no',
  'www.siste.no',
  'www.smaalenene.no',
  'www.svelviksposten.no',
  'www.ta.no',
  'www.tb.no',
  'www.telen.no',
  'www.tk.no',
  'www.tvedestrandsposten.no',
  'www.vest24.no',
  'www.vestbyavis.no',
  'www.vestviken24.no',
];

var amediaPublications = amediaDomains.map(function (domain) {
  return domain.split('.')[1];
});

module.exports = {
  amediaDomains: amediaDomains,
  amediaPublications: amediaPublications
};
